### ISSUE TITLE
Reported large increase in memory usage

### ISSUE THREAD

**Issue by rburchell** [rburchell/literm#15]
> memory usage almost doubled from RSS 34M -> 62M.

I'd like to know what https://github.com/rburchell/dotfiles/blob/master/bin/rssanalyse.pl has to say about the two. I'm not too surprised that it is higher (after all, we are creating a massive grid of QtQuick items), but this seems a bit excessive.

If it is a problem, we could consider to allocate items in demand from a more "global" pool, rather than using a literal screen grid of items. And perhaps we ought to do this for desktop's sake anyway (where the grid will be much larger).

**Comment by pvuorela** [comment]
Freshly started Literm:
Total mapped memory:     163008 kB
    of which is padding: 7856 kB
   of which swapped out: 0 kB
  of which likely stack: 136 kB mapped, 40 kB resident (40 kB main, 0 kB aux threads)
  of which are resident: 65316 kB, 50371 kB proportionally shared
        total anonymous: 45740 kB (70.0%)
                 Shared: 16892 kB total (25.9% of RSS)
              Breakdown: 16144 kB clean (95.6%), 748 kB dirty (4.4%)
                         15632 kB code (92.5%), 500 kB RO data (3.0%), 760 kB RW data (4.5%)
                         0 kB heap (0.0%), 0 kB stack (0.0%), 0 kB other (0.0%)
                Private: 48424 kB total (74.1% of RSS)
              Breakdown: 224 kB clean (0.5%), 48200 kB dirty (99.5%)
                         224 kB code (0.5%), 460 kB RO data (0.9%), 3572 kB RW data (7.4%)
                         43804 kB heap (90.5%), 40 kB stack (0.1%), 324 kB other (0.7%)

Same on Fingerterm for comparison:
Total mapped memory:     131552 kB
    of which is padding: 7048 kB
   of which swapped out: 0 kB
  of which likely stack: 136 kB mapped, 48 kB resident (48 kB main, 0 kB aux threads)
  of which are resident: 35540 kB, 19524 kB proportionally shared
        total anonymous: 14188 kB (39.9%)
                 Shared: 19236 kB total (54.1% of RSS)
              Breakdown: 15248 kB clean (79.3%), 3988 kB dirty (20.7%)
                         14764 kB code (76.8%), 472 kB RO data (2.5%), 4000 kB RW data (20.8%)
                         0 kB heap (0.0%), 0 kB stack (0.0%), 0 kB other (0.0%)
                Private: 16304 kB total (45.9% of RSS)
              Breakdown: 124 kB clean (0.8%), 16180 kB dirty (99.2%)
                         124 kB code (0.8%), 460 kB RO data (2.8%), 3100 kB RW data (19.0%)
                         12264 kB heap (75.2%), 48 kB stack (0.3%), 308 kB other (1.9%)

**Comment by pvuorela** [comment]
Tested how much the TextRenderer delegates affect memory usage. Commenting out instantiation of cellDelegates dropped total anonymous from 45740 to 40860, and further commenting out also cellContentDelegates dropped to 11084.

But... stashing above changes and simplifying cellContentsDelegate to be just Text without blinking got me to 23716. Quite an expensive feature there.

**Comment by rburchell** [comment]
Very good find. I'm not completely surprised, but I'd be lying if I said that I wasn't surprised at all.

I had been thinking for a while about having a blinkOpacity prop in TextRender, driven by a single Animation on the TextRender rather than per-delegate. I'll give that a shot and I guess the result should be quite good then.

That, plus better delegate pooling, should put things in a pretty good state.

**Comment by pvuorela** [comment]
How much there is need to have separate delegate for cell backgrounds? Wonder how much it would save replacing Rectangle {} with QSGSimpleRectNodes.

**Comment by rburchell** [comment]
Using rect nodes would definitely help, at the cost of a slightly less flexible "API", but I think that it should probably be more reasonable with the current pooling introduced now (as there probably won't be many backgrounds, except in pathological cases that try paint each cell separately).

I'm fine with doing that if we still need to, though.

**Comment by pvuorela** [comment]
Not that burning need anymore for saving extra memory, but I'm lacking some imagination for what that flexible api could be used for. At least roundings, transitions etc don't feel that well fitting for terminal cell grid background.

**Comment by rburchell** [comment]
A prototype of this is now done on the render-background-efficiency branch, since I just happened to be looking at this code anyway. I don't notice any major difference in resource usage, so I think I'll close this for the time being, but might go back and merge that later on (if my interests ever return to this code enough).
