### ISSUE TITLE
Misaligned text with DejaVu Sans Mono

### ISSUE THREAD

**Issue by special** [rburchell/literm#4]
Sorry, I don't have a screenshot of this at the moment.

I'm getting misaligned text with the default font selection on fedora25/gnome. The cursor isn't aligned with characters, colored blocks of text are overlapping, and applications like vim are cutting off on the right edge.

The selected font was DejaVu Sans Mono, pixelSize 19, pointSizeF 14.25. iFontHeight/iFontWidth/iFontDescent are 22/11/4.

**Comment by rburchell** [comment]
Summary: it seems like maxWidth is a lie on that font and system, though it works for me. averageCharWidth works, but is less reliable.

Need to figure out why and how to solve it.
