### ISSUE TITLE
qmlRegisterSingletonInstance not declared 

### ISSUE THREAD

**Issue by levone1** [rburchell/literm#41]
make failed with 
`…/literm on  master [!]
67% [ 23:45:45 ] ➜ qmake && make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DD
ESKTOP_BUILD -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_G
UI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_L
IB -I. -I. -isystem /usr/include/qt5 -isystem /u
sr/include/qt5/QtQuick -isystem /usr/include/qt5
/QtGui -isystem /usr/include/qt5/QtQml -isystem
/usr/include/qt5/QtNetwork -isystem /usr/include
/qt5/QtCore -I.moc -I/usr/share/qt5/mkspecs/linu
x-g++ -o .obj/main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:85:5: error: ‘qmlRegisterSingletonInsta
nce’ was not declared in this scope
qmlRegisterSingletonInstance("literm", 1, 0
, "Util", &util);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:85:5: note: suggested alternative: ‘qml
RegisterSingletonType’
qmlRegisterSingletonInstance("literm", 1, 0
, "Util", &util);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
qmlRegisterSingletonType
make: *** [Makefile:398: .obj/main.o] Error 1`

Tried replacing `qmlRegisterSingletonInstance` with `qmlRegisterSingletonType` as suggested in output, but just led to a different error...

**Comment by rburchell** [comment]
qmlRegisterSingletonInstance was added in Qt 5.14, so you need that, or 5.15.
